### ISSUE TITLE
PATH not set to include tabcmd binary

### ISSUE THREAD

**Issue by rusq** [tableau/tableau-docker-samples#4]
Baked image does not have the `tabcmd` on the path, which is a bit frustrating when attempting to use the example out of the box.

Solution is simple - add the following line to the line 7 of the [Dockerfile][1]:

```
ENV PATH="/opt/tableau/tabcmd/bin:${PATH}"
```

[1]: https://github.com/tableau/tableau-docker-samples/blob/master/samples/tabcmd/Dockerfile

**Comment by Tuatan** [comment]
Thanks for reporting the issue, @rusq

**Comment by Tuatan** [comment]
The fix was merged into the master
